apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-vault-api
  namespace: {{ .Values.namespace }}
  labels:
    app: md-vault-api
    {{- include "md-vault.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: md-vault-api
  template:
    metadata:
      labels:
        app: md-vault-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.api.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: md-vault-config
            - secretRef:
                name: md-vault-secrets
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: md-vault-data
