apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-vault-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: md-vault-frontend
    {{- include "md-vault.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: md-vault-frontend
  template:
    metadata:
      labels:
        app: md-vault-frontend
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 101
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 3
            periodSeconds: 10
