apiVersion: v1
kind: Service
metadata:
  name: md-vault-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "md-vault.labels" . | nindent 4 }}
spec:
  selector:
    app: md-vault-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
