apiVersion: v1
kind: PersistentVolume
metadata:
  name: md-vault-pv
  labels:
    app: md-vault
    {{- include "md-vault.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  hostPath:
    path: {{ .Values.storage.hostPath }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: md-vault-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "md-vault.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
